"use client";

import { useMemo, useState } from "react";

type Entry = { id: string; title: string; family: string; scope: string; meaning: string; touchpoint: string; next: string };
const entries: Entry[] = [
  { id: "L-01", title: "A written agreement", family: "contracts", scope: "general orientation", meaning: "A shared record of what each party has agreed to do, when, and under which conditions.", touchpoint: "Before work begins, compare the promise, deliverable, timing, and change process.", next: "Which terms would be difficult to prove if the relationship became unclear?" },
  { id: "L-02", title: "Notice and response", family: "process", scope: "general orientation", meaning: "A formal process often depends on what was communicated, when it was received, and how a response was invited.", touchpoint: "Keep the original notice, delivery evidence, and the response deadline together.", next: "What is the actual source of the deadline, and who can confirm it?" },
  { id: "L-03", title: "Personal data purpose", family: "privacy", scope: "general orientation", meaning: "Collecting information should have a clear purpose, a defined use, and a way for people to understand what happens next.", touchpoint: "Map the fields, purpose, retention period, and access before collecting data.", next: "What is the smallest amount of data needed for the stated purpose?" },
  { id: "L-04", title: "Intellectual work", family: "creative work", scope: "general orientation", meaning: "A creative output can carry different rights and permissions depending on who made it and what was agreed.", touchpoint: "Separate ownership, permission to use, credit, and modification rights in the brief.", next: "Which right is actually needed for the next use, rather than all rights by default?" },
  { id: "L-05", title: "A service boundary", family: "business", scope: "general orientation", meaning: "A clear boundary says what is included, what is excluded, and how a new request changes the work.", touchpoint: "Write the scope, acceptance signal, revision limit, and escalation path in plain language.", next: "What would count as accepted, and who has authority to say so?" },
];
const families = ["all", ...Array.from(new Set(entries.map((entry) => entry.family)))];

export default function Home() {
  const [query, setQuery] = useState("");
  const [family, setFamily] = useState("all");
  const [selectedId, setSelectedId] = useState(entries[0].id);
  const visible = useMemo(() => entries.filter((entry) => { const matchesFamily = family === "all" || entry.family === family; return matchesFamily && `${entry.title} ${entry.meaning} ${entry.family}`.toLowerCase().includes(query.toLowerCase()); }), [family, query]);
  const selected = entries.find((entry) => entry.id === selectedId) ?? visible[0] ?? entries[0];
  return <main className="library"><header className="library-header"><a href="#catalogue" className="seal">PKB <span>§</span></a><div><span>PUBLIC KNOWLEDGE / ORIENTATION NOTES</span><small>Edition 01 · Scope is visible</small></div><span className="year">2026</span></header><section className="library-intro"><p className="kicker">PLAIN LANGUAGE / CLEARER NEXT QUESTIONS</p><h1>Read the<br /><i>fine</i> print.</h1><p className="intro-copy">A working index for getting oriented before you ask the question that needs a qualified professional.</p></section><section className="catalogue" id="catalogue"><aside className="catalogue-rail" aria-label="Legal topic filters"><label htmlFor="entry-search">Search the index</label><input id="entry-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="topic, word, phrase" /><div className="rail-label">TOPIC FAMILY</div>{families.map((item) => <button key={item} className={family === item ? "family active" : "family"} onClick={() => setFamily(item)} aria-pressed={family === item}><span>{item}</span><small>{item === "all" ? entries.length : entries.filter((entry) => entry.family === item).length}</small></button>)}<div className="rail-warning"><strong>Important boundary</strong><br />These are self-authored orientation notes, not current legal advice. Scope and jurisdiction always matter.</div></aside><section className="index-list" aria-label="Legal entries"><div className="index-head"><span>CATALOGUE / {visible.length} RESULTS</span><span>SELECT ONE</span></div>{visible.map((entry) => <button key={entry.id} className={selected.id === entry.id ? "entry active" : "entry"} onClick={() => setSelectedId(entry.id)}><span>{entry.id}</span><strong>{entry.title}</strong><small>{entry.family}</small><i>↗</i></button>)}{visible.length === 0 && <p className="no-result">No entry matches. Try a broader search term.</p>}</section><article className="law-sheet" aria-live="polite"><div className="sheet-rule" /><div className="sheet-head"><span>{selected.id}</span><span>{selected.scope}</span></div><h2>{selected.title}</h2><p className="meaning">{selected.meaning}</p><div className="sheet-row"><span>DOCUMENT TOUCHPOINT</span><p>{selected.touchpoint}</p></div><div className="sheet-row next-question"><span>NEXT QUESTION</span><p>{selected.next}</p></div><div className="sheet-footer"><span>GENERAL ORIENTATION ONLY</span><span>CHECK CURRENT LAW ↗</span></div></article></section><footer><span>PUBLIC KNOWLEDGE / LEGAL ORIENTATION</span><span>Not legal advice · not attorney reviewed</span></footer></main>;
}
